apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frequent-flyer-native
  namespace: kogito-knative
spec:
  template:
    metadata:
      name: frequent-flyer-native-template
    spec:
      containers:
        - image: >-
            quay.io/mouachan/frequent-flyer:native-1.0
  traffic:
    - tag: 'native-1.0'
      percent: 50
      revisionName: frequent-flyer-native-v1
    - tag: 'native-2.0'
      percent: 50
      revisionName: frequent-flyer-native-v2
